version: '3.9'
services: 
  app:
    container_name: app
    restart: always
    build: .
    ports: 
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    restart: always
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: travel_time
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes: 
      - ./data/sqls:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql --host=127.0.0.1 --user=root --password=$$MYSQL_ROOT_PASSWORD --silent --execute \"SELECT 1;\"  || exit 0"]
      interval: 30s
      timeout: 30s
      retries: 5
